---
kind: Service
apiVersion: v1
metadata:
  name: cyberchef
spec:
  selector:
    app: cyberchef
  ports:
    - port: 80
      targetPort: 8000

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: cyberchef
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cyberchef
  template:
    metadata:
      name: cyberchef
      labels:
        app: cyberchef
    spec:
      containers:
        - name: cyberchef
          image: mpepping/cyberchef
          ports:
            - containerPort: 8000
