apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cc
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    external-dns.alpha.kubernetes.io/hostname: "cc.arleskog.se"
spec:
  tls:
  - hosts:
    - cc.arleskog.se
    secretName: cyberchef-arleskog-se-cert
  rules:
  - host: cc.arleskog.se
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: cyberchef
            port:
              number: 80

---
kind: Service
apiVersion: v1
metadata:
  name: cyberchef
spec:
  selector:
    app: cyberchef
  ports:
    - port: 80
      targetPort: 8000

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: cyberchef
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cyberchef
  template:
    metadata:
      name: cyberchef
      labels:
        app: cyberchef
    spec:
      containers:
        - name: cyberchef
          image: mpepping/cyberchef
          ports:
            - containerPort: 8000
