apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://argoproj.github.io/argo-helm'
    targetRevision: 5.27.2
    chart: argo-cd
    helm:
      values: |
        dex:
          enabled: false
        server:
          # certificate:
          #   enabled: true
          #   domain: "argocd.arleskog.se"
          #   issuer:
          #     kind: "ClusterIssuer"
          #     name: letsencrypt-stag
          ingress:
            enabled: true
            ingressClassName: "nginx"
            annotations:
              nginx.ingress.kubernetes.io/backend-protocol: "https"
              cert-manager.io/cluster-issuer: "letsencrypt-prod"
              external-dns.alpha.kubernetes.io/hostname: "argocd.arleskog.se"
            hosts:
              - "argocd.arleskog.se"
            tls:
              - secretName: argocd-arleskog-se-cert
                hosts:
                  - argocd.arleskog.se
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - Replace=true
