apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://argoproj.github.io/argo-helm'
    targetRevision: 5.51.2
    chart: argo-cd
    helm:
      values: |
        configs:
          cm:
            url: "https://argocd.arleskog.se"
            oidc.config: |
              name: Keycloak
              issuer: https://auth.arleskog.se/realms/default
              clientID: argocd
              clientSecret: $oidc.keycloak.clientSecret
              requestedScopes: ["openid", "profile", "email", "roles"]
            admin.enabled: false
          rbac:
            policy.csv: |
              g, admin, role:admin
            scopes: "[roles]"
        dex:
          enabled: false
        server:
          ingress:
            enabled: true
            ingressClassName: "nginx"
            annotations:
              nginx.ingress.kubernetes.io/backend-protocol: "https"
              cert-manager.io/cluster-issuer: "letsencrypt-prod"
              external-dns.alpha.kubernetes.io/hostname: "argocd.arleskog.se"
            hosts:
              - "argocd.arleskog.se"
            tls:
              - secretName: argocd-arleskog-se-cert
                hosts:
                  - argocd.arleskog.se
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - CreateNamespace=true
    - Replace=true

