apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: calibre-web
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: {{ .Values.spec.source.repoURL }}
    path: apps/calibre-web/manifests
    targetRevision: HEAD
  destination:
    namespace: calibre-web
    server: {{ .Values.spec.destination.server }}
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
