apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://charts.jetstack.io
      targetRevision: 1.11.0
      chart: cert-manager
      helm:
        values: |
          installCRDs: true
          prometheus:
            enabled: true
            servicemonitor:
              enabled: true
    - repoURL: {{ .Values.spec.source.repoURL }}
      path: apps/cert-manager
      targetRevision: HEAD
  destination:
    namespace: cert-manager
    server: {{ .Values.spec.destination.server }}
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - CreateNamespace=true
