apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fluent-bit
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://fluent.github.io/helm-charts
    targetRevision: 0.37.0
    chart: fluent-bit
    helm:
      values: |
        config:
          inputs: |
            [INPUT]
                name cpu
                tag  cpu
                interval_sec 1
            [INPUT]
                Name tail
                Path /var/log/containers/*.log
                multiline.parser docker, cri
                Tag kube.*
                Mem_Buf_Limit 50MB
                Skip_Long_Lines On
                Parser cri
            [INPUT]
                Name systemd
                Tag host.*
                Systemd_Filter _SYSTEMD_UNIT=kubelet.service
                Read_From_Tail On
          customParsers: |
          filters: |
            [FILTER]
                Name kubernetes
                Match kube.*
                Merge_Log On
                Keep_Log Off
                K8S-Logging.Parser On
                K8S-Logging.Exclude On
            [FILTER]
                Name rewrite_tag
                Match kube.*
                Rule $message ^[\d\.]+\s-\s[\w\-]+\s[\[\w\d\/:\s+\]]+\s"(HEAD|POST|GET|PUT|DELETE)\s[\d\w\/\.\=\?\-]*\s(HTTP)\/\d\.\d"\s\d{3}\s\d+\s"[\w\d\.\-\/]+"\s"[\w\d\.\-\/\s()]*"\s\d+\s[\d\.]+\s\[[\d\w\-]*\]\s\[[\d\w\-]*\]\s[\w\d\-\/\.:]+\s[\d\-]+\s[\d\-\.]+\s[\d\-]+\s[\d\w]*$ logs.ingress-nginx false
            [FILTER]
                Name parser
                Match logs.ingress-nginx
                Key_Name message
                Parser nginx
                Reserve_Data true
          outputs: |
            [OUTPUT]
                Match logs.ingress-nginx
                tls On
                tls.verify Off
                Name opensearch
                Host opensearch-cluster-headless.opensearch.svc.cluster.local
                Buffer_Size 512KB
                HTTP_User fluent-bit
                HTTP_Passwd ${HTTP_PASSWORD}
                Logstash_Format On
                Logstash_Prefix ingress-nginx-logs
                Replace_Dots On
                Suppress_Type_Name On
                Trace_Error true
            [OUTPUT]
                Name es
                Match kube.*
                Host opensearch-cluster-headless.opensearch.svc.cluster.local
                Logstash_Format On
                tls On
                tls.verify Off
                Buffer_Size 128KB
                HTTP_User fluent-bit
                HTTP_Passwd ${HTTP_PASSWORD}
                Suppress_Type_Name On
                Replace_Dots On
                Trace_Error true
            [OUTPUT]
                Name es
                Match host.*
                Host opensearch-cluster-headless.opensearch.svc.cluster.local
                Logstash_Format On
                Logstash_Prefix node
                tls On
                tls.verify Off
                Buffer_Size 128KB
                HTTP_User fluent-bit
                HTTP_Passwd ${HTTP_PASSWORD}
                Suppress_Type_Name On
                Replace_Dots On
                Trace_Error true
        daemonSetVolumes:
          - name: varlog
            hostPath:
              path: /var/log
          - name: etcmachineid
            hostPath:
              path: /etc/machine-id
              type: File
        daemonSetVolumeMounts:
          - name: varlog
            mountPath: /var/log
            readOnly: true
          - name: etcmachineid
            mountPath: /etc/machine-id
            readOnly: true
        env:
          - name: HTTP_PASSWORD
            valueFrom:
              secretKeyRef:
                name: fluent-bit
                key: HTTP_PASSWORD
                optional: false
  destination:
    namespace: fluent-bit
    server: {{ .Values.spec.destination.server }}
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
