apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://charts.longhorn.io
    targetRevision: 1.4.2
    chart: longhorn
    helm:
      values: |
        defaultSettings:
          backupTarget: "s3://longhorn-private@s3.us-east-005.backblazeb2.com/"
          backupTargetCredentialSecret: backblaze
          backupstorePollInterval: 0
          replicaAutoBalance: best-effort
          defaultDataLocality: best-effort
          orphanAutoDeletion: true
          snapshotDataIntegrityImmediateCheckAfterSnapshotCreation: true
  destination:
    namespace: longhorn-system
    server: {{ .Values.spec.destination.server }}
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - CreateNamespace=true
