apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://metallb.github.io/metallb
      targetRevision: 0.13.7
      chart: metallb
      helm:
        values: |
          speaker:
            enabled: false
    - repoURL: {{ .Values.spec.source.repoURL }}
      path: apps/metallb
      targetRevision: HEAD
  destination:
    namespace: metallb-system
    server: {{ .Values.spec.destination.server }}
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - CreateNamespace=true
