apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://charts.min.io/
    targetRevision: 5.0.9
    chart: minio
    helm:
      values: |
        replicas: 2
        persistence:
          storageClass: "longhorn"
          size: 5Gi
        ingress:
          enabled: true
          ingressClassName: "nginx"
          annotations:
            cert-manager.io/cluster-issuer: "letsencrypt-prod"
            external-dns.alpha.kubernetes.io/hostname: "minio.arleskog.se"
          hosts:
            - minio.arleskog.se
          tls:
            - secretName: minio-arleskog-se-cert
              hosts:
                - minio.arleskog.se
        consoleIngress:
          enabled: true
          ingressClassName: "nginx"
          annotations:
            cert-manager.io/cluster-issuer: "letsencrypt-prod"
            external-dns.alpha.kubernetes.io/hostname: "console.minio.arleskog.se"
          hosts:
            - console.minio.arleskog.se
          tls:
            - secretName: console-minio-arleskog-se-cert
              hosts:
                - console.minio.arleskog.se
        resources:
          requests:
            memory: 256Mi
  destination:
    namespace: minio
    server: {{ .Values.spec.destination.server }}
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
