apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://charts.min.io/
    targetRevision: 5.0.13
    chart: minio
    helm:
      values: |
        replicas: 3
        persistence:
          storageClass: "longhorn"
          size: 8Gi
        ingress:
          enabled: true
          ingressClassName: "nginx"
          annotations:
            cert-manager.io/cluster-issuer: "letsencrypt-prod"
            external-dns.alpha.kubernetes.io/hostname: "s3.arleskog.se"
          hosts:
            - s3.arleskog.se
          tls:
            - secretName: s3-arleskog-se-cert
              hosts:
                - s3.arleskog.se
        consoleIngress:
          enabled: true
          ingressClassName: "nginx"
          annotations:
            cert-manager.io/cluster-issuer: "letsencrypt-prod"
            external-dns.alpha.kubernetes.io/hostname: "console.s3.arleskog.se"
          hosts:
            - console.s3.arleskog.se
          tls:
            - secretName: console-s3-arleskog-se-cert
              hosts:
                - console.s3.arleskog.se
        resources:
          requests:
            memory: 256Mi
  destination:
    namespace: minio
    server: {{ .Values.spec.destination.server }}
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
