apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://helm.releases.hashicorp.com
    targetRevision: 0.25.0
    chart: vault
    helm:
      values: |
        server:
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                  - matchExpressions:
                      - key: kubernetes.io/hostname
                        operator: In
                        values:
                          - hetzner-fsn1-cax21-0.arleskog.se
            podAntiAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                - labelSelector:
                    matchLabels:
                      app.kubernetes.io/name: "vault"
                      app.kubernetes.io/instance: "vault"
                      component: server
                  topologyKey: kubernetes.io/hostname
          ha:
            replicas: 1
            enabled: true
            raft:
              enabled: true
          ingress:
            enabled: true
            annotations:
              cert-manager.io/cluster-issuer: "letsencrypt-prod"
              external-dns.alpha.kubernetes.io/hostname: "vault.arleskog.se"
            hosts:
              - host: vault.arleskog.se
            tls:
              - secretName: vault-arleskog-se-cert
                hosts:
                  - vault.arleskog.se
          dataStorage:
            size: 4Gi
            storageClass: longhorn
        ui:
          enabled: true
  destination:
    namespace: vault
    server: {{ .Values.spec.destination.server }}
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - CreateNamespace=true
