apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://helm.releases.hashicorp.com
    targetRevision: 0.27.0
    chart: vault
    helm:
      values: |
        server:
          ha:
            replicas: 3
            enabled: true
            raft:
              enabled: true
              config: |
                ui = true

                listener "tcp" {
                  tls_disable = 1
                  address = "[::]:8200"
                  cluster_address = "[::]:8201"
                  # Enable unauthenticated metrics access (necessary for Prometheus Operator)
                  #telemetry {
                  #  unauthenticated_metrics_access = "true"
                  #}
                }

                storage "raft" {
                  path = "/vault/data"
                }

                service_registration "kubernetes" {}

                seal "transit" {
                  address = "http://vault-kms-active.vault-kms.svc.cluster.local:8200"
                  disable_renewal = "false"
                  key_name = "autounseal"
                  mount_path = "transit/"
                  tls_skip_verify = "true"
                }
          extraSecretEnvironmentVars:
            - envName: VAULT_TOKEN
              secretName: vault
              secretKey: VAULT_TOKEN
          ingress:
            ingressClassName: nginx
            enabled: true
            annotations:
              cert-manager.io/cluster-issuer: "letsencrypt-prod"
              external-dns.alpha.kubernetes.io/hostname: "vault.arleskog.se"
            hosts:
              - host: vault.arleskog.se
            tls:
              - secretName: vault-arleskog-se-cert
                hosts:
                  - vault.arleskog.se
          dataStorage:
            storageClass: longhorn
        ui:
          enabled: true
  destination:
    namespace: vault
    server: {{ .Values.spec.destination.server }}
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - CreateNamespace=true

