apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault-kms
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://helm.releases.hashicorp.com
    targetRevision: 0.27.0
    chart: vault
    helm:
      values: |
        server:
          affinity: |
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                  - matchExpressions:
                      - key: kubernetes.io/hostname
                        operator: In
                        values:
                            - hetzner-fsn1-cax21-0.arleskog.se
          ha:
            replicas: 1
            enabled: true
            raft:
              enabled: true
          dataStorage:
            size: 256Mi
            storageClass: longhorn
        ui:
          enabled: true
  destination:
    namespace: vault-kms
    server: {{ .Values.spec.destination.server }}
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true

