apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://helm.releases.hashicorp.com
    targetRevision: 0.23.0
    chart: vault
    helm:
      values: |
        server:
          affinity: ""
          ha:
            replicas: 1
            enabled: true
            raft:
              enabled: true
          ingress:
            enabled: true
            annotations:
              cert-manager.io/cluster-issuer: "letsencrypt-prod"
              external-dns.alpha.kubernetes.io/hostname: "vault.arleskog.se"
            hosts:
              - host: vault.arleskog.se
            tls:
              - secretName: vault-arleskog-se-cert
                hosts:
                  - vault.arleskog.se
        ui:
          enabled: true
        csi:
          enabled: true
  destination:
    namespace: vault
    server: {{ .Values.spec.destination.server }}
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - CreateNamespace=true
