apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: translate
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    external-dns.alpha.kubernetes.io/hostname: "translate.arleskog.se"
spec:
  tls:
  - hosts:
    - translate.arleskog.se
    secretName: libretranslate-arleskog-se-cert
  rules:
  - host: translate.arleskog.se
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: libretranslate
            port:
              number: 80

---
kind: Service
apiVersion: v1
metadata:
  name: libretranslate
spec:
  selector:
    app: libretranslate
  ports:
    - port: 80
      targetPort: 5000

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: libretranslate
spec:
  replicas: 1
  selector:
    matchLabels:
      app: libretranslate
  template:
    metadata:
      name: libretranslate
      labels:
        app: libretranslate
    spec:
      containers:
        - name: libretranslate
          image: libretranslate/libretranslate:latest
          ports:
            - containerPort: 5000
          envFrom:
            - configMapRef:
                name: libretranslate
          resources:
            limits:
              memory: "1Gi"
              cpu: "500m"

---
kind: ConfigMap
apiVersion: v1
metadata:
  name: libretranslate
data:
  LT_HOST: '0.0.0.0'
  LT_FRONTEND_LANGUAGE_TARGET: 'sv'
