---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: lldap

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lldap
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 512Mi

---
kind: Service
apiVersion: v1
metadata:
  name: lldap
spec:
  selector:
    app: lldap
  ports:
    - port: 80
      targetPort: 17170
      name: web
    - port: 3890
      targetPort: 3890
      name: ldap

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: lldap
  labels:
    app: lldap
spec:
  selector:
    matchLabels:
      app: lldap
  template:
    metadata:
      labels:
        app: lldap
      annotations:
        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/role: 'lldap'
        vault.hashicorp.com/agent-inject-secret-jwt_secret: 'kv/lldap'
        vault.hashicorp.com/agent-inject-template-jwt_secret: |
          {{- with secret "kv/lldap" -}}
          {{ .Data.data.jwt_secret }}
          {{- end -}}
        vault.hashicorp.com/agent-inject-secret-ldap_user_pass: 'kv/lldap'
        vault.hashicorp.com/agent-inject-template-ldap_user_pass: |
          {{- with secret "kv/lldap" -}}
          {{ .Data.data.ldap_user_pass }}
          {{- end -}}
    spec:
      serviceAccountName: lldap
      containers:
        - name: lldap
          image: nitnelave/lldap:stable
          env:
            - name: UID
              value: "2001"
            - name: GID
              value: "2001"
            - name: TZ
              value: "Europe/Stockholm"
            - name: LLDAP_JWT_SECRET_FILE
              value: "/vault/secrets/jwt_secret"
            - name: LLDAP_LDAP_USER_PASS_FILE
              value: "/vault/secrets/ldap_user_pass"
            - name: LLDAP_LDAP_BASE_DN
              value: "dc=arleskog,dc=se"
          ports:
            - containerPort: 3890
            - containerPort: 17170
          volumeMounts:
            - mountPath: "/data"
              name: data
          resources:
            limits:
              memory: 125Mi
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: lldap
