apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 6.50.7
    chart: grafana
    helm:
      values: |
        datasources:
          datasources.yaml:
            apiVersion: 1
            datasources:
            - name: Prometheus
              type: prometheus
              access: proxy
              url: http://prometheus-server
        persistence:
          enabled: true
          size: 5Gi
        admin:
          existingSecret: grafana
  destination:
    namespace: monitor
    server: {{ .Values.spec.destination.server }}
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - CreateNamespace=true

---
kind: Secret
apiVersion: v1
metadata:
  name: grafana
  namespace: monitor
type: Opaque
stringData:
  admin-user: 'admin'
  admin-password: 'admin'
