spec:
  destination:
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/albertarleskog/argocd
    targetRevision: HEAD

keycloakx:
  ingressAnnotations:
    serverSnippet: |
      {{`location ~* /realms/[^/]+/metrics {
        return 403;
      }`}}
  podAnnotations:
    agentInjectTemplateKeycloak: |
      {{`{{- with secret "kv/keycloak" -}}
      {{ .Data.data.db_password }}
      {{- end -}}`}}
