apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflared
  namespace: default
spec:
  encryptedData:
    TUNNEL_TOKEN: AgAMp/yRTdLB2hPDYitDBpQGbFlq7rXVPTtkA2nyuNRuQL07IwUjJ8aarH9yoxzPgmxfyH6RkIUR53RUDbuNm6SRoJrCA9irLaJQ/pB+pjdZhP07wuu5UOBXwfC18edmx7ne5gq3mnqKXUZAA2y9V2Fo3g/FUNfzsPJlp/Mt0fq31WJLsEbs3uLHwcVt6djv1XA0jGMAhA5+YocqLasVoff1W0vvIsIvSjawk68Q/c1BmeAhsbObbTEfg/87Yavv+aXH/YFlStkHVgG4UgzYDQTTaooSPCGyNjozSjlFone/CcpiUkEMuKbtdMAfD7EWCUr+jOLhW2z/RJAh/N6+TzGYVoC8WWwWpoE5PS/RHw/MvnurVMhce2Ol+dKMywiXnynlFYZ9NR3wxQ4FNTRUZcY0BhmNw+4MefulSCILLskVO9DnSuJx4ijfHzefzs+tH5GoLhpul3BDsdazESDTn8hbT/OvtnTMeLOZBZMhTmVFd0zsERDnEvOsjLUl0iN4jxsg3U7qpoeya1SqAbe6aIlli7r4aKGZ8dhbFTL7favfXq0ti9wTJzBWqgwK9HBPJ0ZX7ESU+e4Vuz2U/ReT0yHz76okV8iewHoxV3QKH7znHxI7fnglf6zYVH/W5gDZDMyGVnkqZmqq9GNrsiz0x44+wArrQXw4Kn7sLD2eLrQZWRuMxL25jZC9kTUxbFv0caanokohA1woDoPovzpZDglU6KkHq0kWhm1+P5CtYxFrfhlWiutcga83UB7MdX3dn+jBx0/PuurKIPyEsF6UwH7UlIse46io00PT66Fk/ggIer17+X2Go5AzL/YgOT9D0c5zCqT017g04n+mHUu8dxgC7Yp/MoqQ7AYjoOImbP2waa3hz2hBarEVsyvsTc7RxM4yE87LDO8ZlGq9qp5fme5XcHtAj8eTXMO442Hep5VT+Zb++tJvWum4
  template:
    metadata:
      creationTimestamp: null
      name: cloudflared
      namespace: default
    type: Opaque

---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: cloudflared
  labels:
    app: cloudflared
spec:
  selector:
    matchLabels:
      pod: cloudflared
  template:
    metadata:
      labels:
        pod: cloudflared
    spec:
      containers:
      - image: cloudflare/cloudflared:latest
        name: cloudflared
        envFrom:
        - secretRef:
            name: cloudflared
        args:
        - 'tunnel'
        - '--metrics'
        - '0.0.0.0:2000'
        - 'run'
        livenessProbe:
          httpGet:
          # Cloudflared has a /ready endpoint which returns 200 if and only if
          # it has an active connection to the edge.
            path: /ready
            port: 2000
          failureThreshold: 3
          initialDelaySeconds: 30
          periodSeconds: 10
